name: lectures
channels:
  - defaults
dependencies:
  - argon2-cffi
  - async_generator
  - attrs
  - backcall
  - bleach
  - ca-certificates
  - certifi
  - cffi
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - icu
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab_pygments
  - jupyterlab_widgets
  - libcxx
  - libffi
  - libpng
  - libsodium
  - markupsafe
  - matplotlib-inline
  - mistune
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - openssl
  - packaging
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pip
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - ptyprocess
  - pycparser
  - pygments
  - pyparsing
  - pyqt
  - pyrsistent
  - python
  - python-dateutil
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - readline
  - send2trash
  - setuptools
  - sip
  - six
  - sqlite
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - tzdata
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xz
  - zeromq
  - zipp
  - zlib
